seed: 42
device: cuda
data_dir: data/voxceleb1
debug: False
batch_size_train: 32
batch_size_valid: 32
num_workers: 0
max_epochs: 5
n_saved: 3
save_every_iters: 1000
patience: 2
log_every_iters: 10
lr: 0.0002
features:
  n_mels: 24
model:
  model_name: baseline
  in_channels: ${features.n_mels}
